### ISSUE TITLE
Is there a "jQuery free" branch/fork of ui-select2?

### ISSUE THREAD

**Issue by ozomer** [angular-ui/ui-select2#100]
I used to think Angular suppose to replace jQuery, but now I notice that more and more modules require both.

Isn't jqLite enough?
I'm trying to avoid loading both libraries.

**Comment by kadamwhite** [comment]
ui-select2 provides Angular bindings for [the jQuery Select2 plugin](http://ivaynberg.github.io/select2/); because of this it does require the full version of jQuery.

jqLite is great for letting Angular run on its own, but for more advanced functionality jQuery is going to come in handy sooner or later.

**Comment by dimirc** [comment]
We are working on [new native directive](https://github.com/angular-ui/ui-select/issues/3) with similar functionalities that won't have these dependencies. Check #82
