### ISSUE TITLE
Issue with displaying model items on load

### ISSUE THREAD

**Issue by levyuk** [angular-ui/ui-select2#22]
Hi

When the page loads the items in the ng-model aren't showing in the list. The SELECT is set to multiple.

It's only when I select items that they show. The ng-model is correct so just wondering if there is something I'm missing.

**Comment by davidagraf** [comment]
Hi

I might have a similar problem, see: http://stackoverflow.com/questions/16913380/angular-ui-select2-showing-preselected-value-doesnt-work

**Comment by mozerov** [comment]
I have the same issue. Any plans to fix/explain why is it working this way?

**Comment by adiroiban** [comment]
This is also related to this: https://github.com/angular-ui/angular-ui/issues/409 , example here http://jsfiddle.net/maxl/hWXBv/14/

The problem is that ui-select2 is initialed with an error of Strings and at first change it is transferd into an array of Objects.

It would make sense to allow initializing the ui-select with an array of Objects.

**Comment by adiroiban** [comment]
I have created a minimal example, and it looks like when using latest select2 3.4.0 the model can be initialized with an array of objects: http://jsfiddle.net/hWXBv/24/

**Comment by davidagraf** [comment]
@adiroiban Thanks for your input. It almost solves my problem. But not entirely because my select box options are dynamic. Here is a demo: http://plnkr.co/edit/ohCTPtQGfweJOltLRcJX

When you click on the button, the select box options are not updated properly.

**Comment by adiroiban** [comment]
plunkr sucks http://plnkr.co/edit/nEMj1Je6frj6xjetXetp :)

Here is your problem. This is a generic problem about programming and pointer. You can  not just replace the entire array, as angular keep listening for changes on the array that was designed at initialization point.

Use angular.copy() to update any watched object without destroying it.

```
angular.copy([
      {
        text : 'david',
        id : 1
      },
      {
        text : 'hugo',
        id : 2
      }
    ],$scope.options);

    $scope.selected = $scope.options[1];
  };

```

**Comment by davidagraf** [comment]
Yep. Plunkr sucks sometimes. I am having a love-hate relationship to it ...

Thanks for your help! Works!

Since you seem to be the master of select2, I take the opportunity to ask another question :-). What am I doing wrong here: http://plnkr.co/edit/RJKdDYtcrFPnwqpi9SKV? Concerning the doku, it should be possible to specify the text which is shown in the dropdown by adding the key 'text' with a function or a name to the options object. 

> Alternatively, this element can be specified as an object in which results key must contain the data as an array and a text key can either be the name of the key in data items that contains text or a function that retrieves the text given a data element from the array

But it doesn't work. Am I doing something wrong?

**Comment by adiroiban** [comment]
Please don't hijack this ticket :)
You have the same problem... **always** use angular.copy to update the $scope.options form model, instead of new variable assignment ( = ).

**Comment by davidagraf** [comment]
I think you misunderstand my problem. To not hijack this ticket even more, I created another ticket here: https://github.com/ivaynberg/select2/issues/1439

**Comment by ProLoser** [comment]
I'm confused...

Anyway, I know there's an unfixed issue with initialization data. I have not for the bloody life of me had time to sort it out. It is a design decision of do I enforce people to pull up entire objects to initialize the data, or do i allow them to use simple strings to do it, etc. And yes, this also means `ui-select2` might change your data almost immediately. It needs to be sorted out by someone who wants to champion this cause.
