### ISSUE TITLE
ng-required doesn't work with input hidden on AJAX configurations

### ISSUE THREAD

**Issue by raff77** [angular-ui/ui-select2#40]
ng-required doesn't work with input hidden on AJAX configurations. Form validation doesn't therefore work eg

```
<input id="search" type='hidden' ui-select2="sOptions" ng-model="selected" ng-required="true" ></input>
```

**Comment by lasimon** [comment]
Having the same issue:

```
<input ui-select2="stageOptions" type="hidden" ng-model="writer.stages" ng-required="true" multiple="multiple"></input>
```

**Comment by lasimon** [comment]
```
<input ui-select2="stageOptions" name="stages" ng-model="writer.stages" multiple ng-required="true" ></input>
 <span style="color:red;" ng-show="PendWriter.stages.$error.required">Required</span>
```

"Required" appears before any items have been added, as expected.  It also disappears when an item is added.  But if all the selected items are removed from the list, the Required does not reappear.

**Comment by antoniomacs** [comment]
Same here.

**Comment by plus-** [comment]
:+1:

**Comment by panga** [comment]
Same problem here.

**Comment by lehabaev** [comment]
Fix it please!

**Comment by goldserg** [comment]
Not work first time for input and setting - multiple: false
I have a case when I've no list to genereta options and I must to type any chars, but select only one of the list.
If I select first time - input become valid, but div still invalid.
If I select second time - both field become valid.

UP1
This occur because the validation check happens during the same phase that change value.
Temporary fix - run second validation after set value to select2.
I know that is not full correct, but in my case it works

**Comment by rajesh38** [comment]
Really a problem
