### ISSUE TITLE
Support ngOptions

### ISSUE THREAD

**Issue by devesh** [angular-ui/ui-select2#46]
Like https://github.com/localytics/angular-chosen.

Alternatively, if there's a very good reason why ngOptions can't or shouldn't be supported that would not be obvious to users of this library, add the explanation the documentation.

**Comment by itsdrewmiller** [comment]
As far as I can tell, this actually worked fine a few months ago.  It is broken in the latest version, though.  I was using the value as an object, applying a filter, and loading the whole array dynamically via ajax.

**Comment by rdniller** [comment]
\+ 1 on this request.

**Comment by rdniller** [comment]
This angularjs select2 directive supports ng-options:

[ngyn](https://github.com/configit/ngyn/blob/master/src/ngyn-select2.js)

**Comment by jrust** [comment]
+1 as well to reduce the number of scopes when using a bunch of select2 boxes on the page.

**Comment by tlrjs** [comment]
+1 on supporting ng-options

**Comment by jkarttunen** [comment]
+1 support for ng-options.
 It gets dirty to work with some select boxes that support returning whole object with ng-model, and then ui-select2 that returns only strings for selected item.

**Comment by dtabuenc** [comment]
The underlying problem is that  with ng-options the value in the model is usually not the same as the actual value in the element. 

Whenever a change is made in the underlying model, ui-select2 tries to tell select2 about it by calling

``` javascript
select2("val", controller.$viewModel)
```

I think a better approach is to let select2 handle that itself. The angular select with the ng-options is still present and working, so it's just a matter of telling select2 to re-read our select and let it figure out which option is selected from there. You can easily do that by triggering a change event on our select. 

I've gotten this to work on some of our projects by replacing a few of the explicit value sets with

``` javascript
tElem.trigger('change')
```

and removing the initial:

``` javascript
e.m.select2('data', controller.$modelValue);
```

I think taking this approach would likely simplify the rest of the ui-select2 directive (probably eliminating a lot of the code for handling multi-selects etc....)

I'm perfectly willing to make the changes and submit a pull request, but I'd like to get some feedback and make sure there's no other things that would be impacted.

**Comment by nfantone** [comment]
+1

**Comment by ptanov** [comment]
Are there any plans to fix this issue?

**Comment by chatellier** [comment]
+1

**Comment by dtabuenc** [comment]
I haven't had time to add documentation or any sort of build system, but I plan to add soon. If you don't mind using an undocumented script you can try this here:

https://github.com/splendidcode/ng-select2

It allows the use of ng-options and makes the use of selct2 much more transparent. I hope to document this this weekend and make it more of an official release.

Here's some examples of usage:

http://plnkr.co/edit/DBVFcf3RBvyrR6lWGEBp?p=preview

**Comment by geminiyellow** [comment]
thanks @dtabuenc , it working.

**Comment by mukgupta** [comment]
@dtabuenc : Thanks! your script saved my day.

**Comment by igler** [comment]
+1

**Comment by bountin** [comment]
+1
With ngOptions one can bind a complex object as model like "country as country.name for country in countries". This is not possible with ng-repeat and ng-value. 
A workaround is to bind on $index and resolve the repeated objects by hand (or register a watcher for it) but this solution is not as nice as angular's.

**Comment by wodka** [comment]
@dtabuenc this works like a charm :)

**Comment by PowerKiKi** [comment]
This project is deprecated. Fixes and new features are **very** unlikely to happen. You should instead consider a migration to https://github.com/angular-ui/ui-select.
