### ISSUE TITLE
Directive should not trigger ng-change

### ISSUE THREAD

**Issue by marfillaster** [angular-ui/ui-select2#84]
Select2 should follow ng-select or ng-input ng-change behavior which is to _not_ trigger when changing the model programatically. Only user interaction with select2 should trigger the directive.

This happens when `initSelection` is used to set default value for remotely fetched values.

**Comment by Sharondio** [comment]
This is also happening to me, and I'm not using the initSelection for default value.  I'm initing with:

$scope.uiSelect2Options = {
    placeholder: "Select Codes"
,   multiple: true
}

And calling with:

<div ng-repeat="item in items">
....
<select multiple="multiple" ui-select2="uiSelect2Options" ng-model="item.codes" ng-change="tag(item)">
    <option ng-repeat="code in codes">{{code}}</option>
</select>
...
</div>

I'm open to any suggestions or workarounds on this one.

**Comment by ni-ka** [comment]
+1 This requires heavy work arounds to deal with...

**Comment by themtok** [comment]
+1 workarounds require hacks like ugly setTimeout...

**Comment by frankalbenesius** [comment]
+1

**Comment by jikson26** [comment]
+1

**Comment by unrealsolver** [comment]
+1

**Comment by mattymess** [comment]
Definitely +1 on this...

Just came across it today while implementing this directive. I'm making an AJAX request on `ng-change`, which updates my model when the request comes back (via `then` function). This causes another AJAX request since `ng-change` is being triggered due to the model update in the `then` function.

**Comment by SebastianMartens** [comment]
+1

**Comment by sroe** [comment]
How did you handle the issue?

**Comment by unrealsolver** [comment]
@sroe, You can switch to `ui-select` or deny first trigger call. Weird, but it's a best solution I've found.

**Comment by sroe** [comment]
@unrealsolver I have 5 select2's on my page, where I'm getting 5 ngChange calls :-1:.
I will check if ui-select passes all my usability test's. But migrating it costs time which I don't have at the moment. A quick fix would be helpful at this time :smile:. 

I will see if I just use a "Init" variable, because I'm only setting model in the init phase of my controller.

**Comment by liminjun** [comment]
About this issue,the official deal with it now?

**Comment by PowerKiKi** [comment]
this project is dead, if you expect new features and/or bugfixes, you should migrate to https://github.com/angular-ui/ui-select
